server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/auth/**,/qry/usuarios/**,/cmd/usuarios/**,/qry/afiliaciones/**,/cmd/afiliaciones/**,/qry/solicitudes-productor/**,/cmd/solicitudes-productor/**
        - id: productos-service
          uri: lb://productos-service
          predicates:
            - Path=/productos/**
        - id: pedidos-carrito
          uri: lb://pedidos-service
          predicates:
            - Path=/carrito/**
        - id: pedidos-service
          uri: lb://pedidos-service
          predicates:
            - Path=/pedidos/**
        - id: pagos-service
          uri: lb://pedidos-service
          predicates:
            - Path=/pagos/**

logging:
  level:
    root: INFO
    com.agromercado.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway

app:
  jwt:
    dev:
      enabled: true
      secret: dev-0123456789abcdef-0123456789abcd

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
